name: Deploy Scaleway Functions

on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    permissions:
      contents: read
    uses: $/.github/workflows/scaleway.yaml
    with:
      directory: function
      function-id: d1c6b167-f6f2-4219-9c9e-2dcec01b3010
    secrets:
      scaleway-token: ${{ secrets.SCW_SECRET_KEY }}
